[project]
name = "
8376_minflux_ALM"
channels = ["conda-forge"]
platforms = ['osx-arm64', 'linux-64']
version = "0.1.0"
authors = ["Maximilian Senftleben <maximilian.senftleben@scilifelab.se>"]
description = "Meeting on 2025-10-17 with the Advanced Light Microscopy facility at SciLifeLab, discussed that there is a need for future image analysis support for data that ALM generates "
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/BIIFSweden/8376_minflux"

[tasks]

[dependencies]
